### ISSUE TITLE
PHP SERVER NOT STARTED. RETRYING...

### ISSUE THREAD

**Issue by sheerazahmadpk** [AJ-TechSoul/ELECTRON-4-PHP#26]
I just use this repo but I am getting this error
PHP SERVER NOT STARTED: RETRYING...

![electron](https://user-images.githubusercontent.com/29297868/98469722-2a02b980-2203-11eb-824a-2a72b56d8bc7.PNG)

and output is showing raw php file

**Comment by AJ-TechSoul** [comment]
Please add the repo to a c drive and also please click on the bat file. in
the root of repo.

**Comment by sheerazahmadpk** [comment]
I follow your steps but I am getting same error

**Comment by Rajeshwaran2001** [comment]
I just use this repo but I am getting this error
PHP SERVER NOT STARTED: RETRYING...
I had the file in c drive only 

> 
![Screenshot (69)](https://user-images.githubusercontent.com/54212165/99255029-4e7d1800-2839-11eb-8533-6b495462b975.png)

**Comment by AJ-TechSoul** [comment]
Please (in Windows) disable antivirus and firewall and also reduce the the
UAC to last down.


let me know.

**Comment by Rajeshwaran2001** [comment]
Hi,

I had the same issue.

I have installed the xampp package, and I had C:\xampp\php in my PATH environment variable.
So the phpinfo() here always showed the PHP installed with xampp.

I removed C:\xampp\php from my PATH in order to see the PHP info which came with the ELECTRON-4-PHP git package. Then it showed

PHP server not started. Retrying...
It works when you change main.js to add the path to the bundled PHP like this:

const server = new PHPServer({
    php: "php\\php.exe",  // <==== ADDED
    port: 5555,
    directory: __dirname,
    directives: {
        display_errors: 1,
        expose_php: 1
    }
});
Perhaps this should just be added to the README file?

Regards
Rajeshwaran

**Comment by AJ-TechSoul** [comment]
Please run .bat file you get with package.

**Comment by Teyk0o** [comment]
> Hi,
> 
> I had the same issue.
> 
> I have installed the xampp package, and I had C:\xampp\php in my PATH environment variable. So the phpinfo() here always showed the PHP installed with xampp.
> 
> I removed C:\xampp\php from my PATH in order to see the PHP info which came with the ELECTRON-4-PHP git package. Then it showed
> 
> PHP server not started. Retrying... It works when you change main.js to add the path to the bundled PHP like this:
> 
> const server = new PHPServer({ php: "php\php.exe", // <==== ADDED port: 5555, directory: __dirname, directives: { display_errors: 1, expose_php: 1 } }); Perhaps this should just be added to the README file?
> 
> Regards Rajeshwaran

This is the solution, thanks !

**Comment by Henry-Turtle** [comment]
I'm using Laravel with this repo, and was getting the same issue. My code in main.js (lines 68-87): 
server = new PHPServer({
php: "${__dirname}/php/php.exe", //Quotation marks there are acually backticks, but Github didn't like it 
port: 5555,
directory: __dirname, 
directives: { 
display_errors: 1, 
expose_php: 1 
} }
); } 

(Github didn't let me format this code for some reason, sorry) 

When I ran this, I got one "PHP server not started. Retrying..." message, then it opened up my app and gave me this message: 
`
Parse error: syntax error, unexpected '=' in C:\Users\thegr\Desktop\ELECTRON-4-PHP\Scouting-Program\vendor\symfony\string\Resources\functions.php on line 34 
`
When I looked up this issue, I came across a stackoverflow post that said the error was caused by a Null Coalescing Assignment Operator, which was introduced in php 7.4. Taking a peek in the bundled php installation, I saw that it was version 7.2, so I deleted the installation and reinstalled my own at current version. I had to uncomment a few extensions, (I just copied my personal php.ini file contents), and renamed the php.ini-development to php.ini (for some reason it wasn't loading otherwise), and my app loaded and worked as intended! Hopefully others find this helpful, even though its a little off  topic for the thread

**Comment by Poreis** [comment]
I'm still getting this issue...
I'm using MacOS and I get this error : 
```
PHP Server error Error: spawn php ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn php',
  path: 'php',
  spawnargs: [
    '-S',
    '127.0.0.1:5555',
    '-t',
    '/Users/pedrogouveia/ELECTRON-4-PHP',
    '-d',
    'display_errors=1',
    '-d',
    'expose_php=1'
  ]
}
PHP Server closed
PHP server not started. Retrying...
```
Maybe this should be fixed.

**Comment by aj-techsoul** [comment]
Check if the administration permission is given.

**Comment by Poreis** [comment]
Dear AJ,

I'm running the program on my mac, and when I run the "sudo npm start" it gives me this error:
```
PHP Server error Error: spawn php ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn php',
  path: 'php',
  spawnargs: [
    '-S',
    '127.0.0.1:5555',
    '-t',
    '/Users/pedrogouveia/Documents/Projectos/phptest/ELECTRON-4-PHP',
    '-d',
    'display_errors=1',
    '-d',
    'expose_php=1'
  ]
}
PHP Server closed
PHP server not started. Retrying...
```

I'm I suppose to have PHP installed? Because in main.js you don't have any path for php if not running in windows. I'm running this command in "sudo". Any idea on why I might be having this issue?

**Comment by Poreis** [comment]
Solved the issue by installing PHP on macOS.

**Comment by aj-techsoul** [comment]
Great, thanks for letting me know.
