### ISSUE TITLE
MacOS error: spawn /php/php.exe EACCES

### ISSUE THREAD

**Issue by Henry-Turtle** [aj-techsoul/ELECTRON-4-PHP#47]
EDIT: There is solved, there is a new issue below. I left this here just for documentation if others have the same problem
Hey there!
I used this repository for windows, and it worked just fine. However, when I transferred the files to MacOS to build for mac, I got a strange error. The log is below:

npm run start

> scouting-app@1.0.0 start
> electron .

PHP Server error Error: spawn php/php.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn php/php.exe',
  path: 'php/php.exe',
  spawnargs: [
    '-S',
    '127.0.0.1:5000',
    '-t',
    '/Users/pheros/Desktop/Scouting-App',
    '-d',
    'display_errors=1',
    '-d',
    'expose_php=1'
  ]
}
PHP Server closed

This is my php server declaration:
server = new PHPServer({
    php: "php/php.exe",
    port: 5000,
    directory: __dirname,
    directives: {
        display_errors: 1,
        expose_php: 1
    }
});

I've seen other people fix their problems with adding that php: "php/php.exe" line, but that didn't solve it for me clearly. How can I fix this error?

**Comment by Henry-Turtle** [comment]
Update: I did "php/php.exe -v" and realized i didn't have permission to run it. After running "chmod +x php/php.exe" I am now only getting one error:
php/php.exe: php/php.exe: cannot execute binary file
Which is...Kind of expected, I guess. How do I execute on Mac? Do I have to bundle Wine as well or something like that?

**Comment by Henry-Turtle** [comment]
I figured out the problem with that too. Once I deleted the php: "php/php.exe" line, everything worked just fine.
